title: Gabe Schenz | Data Engineering Manager | Principal Data Engineer
description: Technical leader specializing in creating architectures and teams focused on scalable and efficient data practices, and strong engineering fundamentals.
